wandb_version: 1

NUM_AGENTS:
  desc: null
  value: 10
BUFFER_SIZE:
  desc: null
  value: 10000
BUFFER_BATCH_SIZE:
  desc: null
  value: 128
SHARED_BATCH_SIZE:
  desc: null
  value: 5
CONNECTIVITY:
  desc: null
  value: fully
TOTAL_TIMESTEPS:
  desc: null
  value: 80000000.0
EPSILON_START:
  desc: null
  value: 1.0
EPSILON_FINISH:
  desc: null
  value: 0.05
EPSILON_ANNEAL_TIME:
  desc: null
  value: 250000.0
TARGET_UPDATE_INTERVAL:
  desc: null
  value: 500
LR:
  desc: null
  value: 0.00025
LEARNING_STARTS:
  desc: null
  value: 10000
TRAINING_INTERVAL:
  desc: null
  value: 10
DIVERSITY_INTERVAL:
  desc: null
  value: 100
PROB_VISIT:
  desc: null
  value: 0.2
VISIT_DURATION:
  desc: null
  value: 0.2
LR_LINEAR_DECAY:
  desc: null
  value: false
GAMMA:
  desc: null
  value: 0.99
TAU:
  desc: null
  value: 1.0
ENV_NAME:
  desc: null
  value: Bestoften-paths-alchemy
SEED:
  desc: null
  value: 1
NUM_SEEDS:
  desc: null
  value: 1
WANDB_MODE:
  desc: null
  value: online
ENTITY:
  desc: null
  value: eleni
PROJECT:
  desc: null
  value: sapiens
project_name:
  desc: null
  value: /sapiens_envBestoften-paths-alchemy_conn_fully_n_10_trial_1
num_eval_trials:
  desc: null
  value: 100
local_mode:
  desc: null
  value: true
project_dir:
  desc: null
  value: projects/2024_10_19//sapiens_envBestoften-paths-alchemy_conn_fully_n_10_trial_1
NUM_NEIGHBORS:
  desc: null
  value: 9
initial_graph:
  desc: null
  value: "[[1 2 3 4 5 6 7 8 9]\n [0 2 3 4 5 6 7 8 9]\n [0 1 3 4 5 6 7 8 9]\n [0 1\
    \ 2 4 5 6 7 8 9]\n [0 1 2 3 5 6 7 8 9]\n [0 1 2 3 4 6 7 8 9]\n [0 1 2 3 4 5 7\
    \ 8 9]\n [0 1 2 3 4 5 6 8 9]\n [0 1 2 3 4 5 6 7 9]\n [0 1 2 3 4 5 6 7 8]]"
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729369060
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.11.0
      5: 0.17.5
      8:
      - 5
      13: darwin-arm64
