wandb_version: 1

NUM_AGENTS:
  desc: null
  value: 20
BUFFER_SIZE:
  desc: null
  value: 10000
BUFFER_BATCH_SIZE:
  desc: null
  value: 128
SHARED_BATCH_SIZE:
  desc: null
  value: 5
CONNECTIVITY:
  desc: null
  value: dynamic
TOTAL_TIMESTEPS:
  desc: null
  value: 800000.0
EPSILON_START:
  desc: null
  value: 1.0
EPSILON_FINISH:
  desc: null
  value: 0.05
EPSILON_ANNEAL_TIME:
  desc: null
  value: 250000.0
TARGET_UPDATE_INTERVAL:
  desc: null
  value: 500
LR:
  desc: null
  value: 0.00025
LEARNING_STARTS:
  desc: null
  value: 10000
TRAINING_INTERVAL:
  desc: null
  value: 10
DIVERSITY_INTERVAL:
  desc: null
  value: 100
PROB_VISIT:
  desc: null
  value: 0.2
VISIT_DURATION:
  desc: null
  value: 0.2
LR_LINEAR_DECAY:
  desc: null
  value: false
GAMMA:
  desc: null
  value: 0.99
TAU:
  desc: null
  value: 1.0
ENV_NAME:
  desc: null
  value: CartPole-v1
SEED:
  desc: null
  value: 0
NUM_SEEDS:
  desc: null
  value: 15
WANDB_MODE:
  desc: null
  value: online
ENTITY:
  desc: null
  value: eleni
PROJECT:
  desc: null
  value: sapiens
NUM_NEIGHBORS:
  desc: null
  value: 2
initial_graph:
  desc: null
  value: "[[ 1 -1]\n [ 0 -1]\n [ 3 -1]\n [ 2 -1]\n [ 5 -1]\n [ 4 -1]\n [ 7 -1]\n [\
    \ 6 -1]\n [ 9 -1]\n [ 8 -1]\n [11 -1]\n [10 -1]\n [13 -1]\n [12 -1]\n [15 -1]\n\
    \ [14 -1]\n [17 -1]\n [16 -1]\n [19 -1]\n [18 -1]]"
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728243540
    t:
      1:
      - 12
      - 45
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.11.0
      5: 0.17.5
      8:
      - 5
      13: darwin-arm64
